### ISSUE TITLE
Ikev2ProfileSetAuth gives error

### ISSUE THREAD

**Issue by zurrehma** [ligato/vpp-agent#1091]
when i want to put data in this [ stuct](https://github.com/ligato/vpp-agent/blob/e874d7dfba888cf2e431a70f4b0fa1d9b828583e/plugins/vpp/binapi/ipsec/ipsec.ba.go#L698) of ikev2 it gives me this error:
```
ERROR: no reply received within the timeout period 1s
vac_disconnect:407: vac_disconnect cnacel
vl_client_disconnect:322: queue drain: 7
msg_handler_internal:432: no handler for msg id 7
vl_client_disconnect:310: peer unresponsive, give up
```

**my data to struct is:**
```go
req:=&ipsec.Ikev2ProfileSetAuth{
    Name : []byte("Profile1"),
    AuthMethod : uint8(2),
    Data : []byte("vpp123"),
}
reply := &ipsec.Ikev2ProfileSetAuthReply{}

if err := ch.SendRequest(req).ReceiveReply(reply); err != nil {
    fmt.Println("ERROR:", err)
    return
}
if reply.Retval != 0 {
    fmt.Println("Retval:", reply.Retval)
    return
}
```

**Comment by ondrej-fabry** [comment]
Does your code work with some other request? Try using simple request like `vpe.ShowVersion` to ensure that you are properly connecting to VPP binary API.

**Comment by ondrej-fabry** [comment]
Does VPP process print amything during request?

**Comment by zurrehma** [comment]
@ondrej-fabry vpp process prints this:
vpp# Aborted (core dumped)

**Comment by ondrej-fabry** [comment]
Your VPP process crashed. You have most likely put some invalid values or unsupported combination in the request and this caused some undefined behavior and the process crash.

How do you run VPP? As a service? Try running it in foreground so you can see all of it's output. It might print some information before the crash. You can also [configure output log file](https://wiki.fd.io/view/VPP/Command-line_Arguments#unix_.7B_..._.7D) for the VPP using `unix { log xxx ... }`.

**Comment by zurrehma** [comment]
@ondrej-fabry Log file is not showing anything, whenever i pass some configurations via govpp.its only show those commands which i set from vpp cli.
the output of log file is like:
2019/ 1/ 8 18:12:03:203: ***** Start: PID 926 *****

2019/ 1/ 8 18:14:55:494: ***** Start: PID 946 *****
2019/ 1/ 8 18:15:01:650[0]: show interface
2019/ 1/ 8 18:15:34:920: ***** Start: PID 952 *****
2019/ 1/ 8 18:16:54:711: ***** Start: PID 967 *****
2019/ 1/ 8 18:17:09:767[0]: sho int2019/ 1/ 8 18:17:12:060[0]: sho in2019/ 1/ 8 
can you tell me according to your understanding what is problem with this req:
req:=&ipsec.Ikev2ProfileSetAuth{
    Name : []byte("Profile1"),
    AuthMethod : uint8(2),
    Data : []byte("vpp123"),
}
and how you will fill this [struct](https://github.com/ligato/vpp-agent/blob/e874d7dfba888cf2e431a70f4b0fa1d9b828583e/plugins/vpp/binapi/ipsec/ipsec.ba.go#L698)?

**Comment by ondrej-fabry** [comment]
Please send your `vpp.conf` file you use for VPP process along with arguments you use please.

**Comment by zurrehma** [comment]
@ondrej-fabry vpp.conf file contain:
unix {
    nodaemon
    cli-listen 0.0.0.0:5002
    cli-no-pager
    log /tmp/vpp.log
    full-coredump
}
plugins {
    plugin dpdk_plugin.so {
        disable
    }
}
api-trace {
    on
}
command line arguments are:
**vpp unix {log /conf.txt interactive }**

**Comment by ondrej-fabry** [comment]
Does the IKEv2 work for you using CLI commands? As far as I know IKEv2 is not completely functional in VPP so I can't tell you if you can make it work at all. Try using CLI commands to set it up first.

**Comment by zurrehma** [comment]
@ondrej-fabry IKEv2 commands which i am using is working fine with cli.
in first shell i am getting this:
vpp[128]: received signal SIGSEGV, PC 0x7f95df712fa9, faulting address 0x34003000
vpp[128]: received signal SIGSEGV, PC 0x7f95df712fa9, faulting address 0x34003000
vpp[128]: #0  0x00007f95dfeba39a 0x7f95dfeba39a
vpp[128]: #0  0x00007f95dfeba39a 0x7f95dfeba39a
vpp[128]: #1  0x00007f95ded48890 0x7f95ded48890
vpp[128]: #1  0x00007f95ded48890 0x7f95ded48890
vpp[128]: #2  0x00007f95df712fa9 0x7f95df712fa9
vpp[128]: #2  0x00007f95df712fa9 0x7f95df712fa9
vpp[128]: #3  0x00007f95e00e0366 vl_msg_api_handler_with_vm_node + 0x66
vpp[128]: #3  0x00007f95e00e0366 vl_msg_api_handler_with_vm_node + 0x66
vpp[128]: #4  0x00007f95e00e76f5 vl_mem_api_handle_msg_main + 0x45
vpp[128]: #4  0x00007f95e00e76f5 vl_mem_api_handle_msg_main + 0x45
vpp[128]: #5  0x00007f95e00f9ba8 0x7f95e00f9ba8
vpp[128]: #5  0x00007f95e00f9ba8 0x7f95e00f9ba8
vpp[128]: #6  0x00007f95dfe7dca6 0x7f95dfe7dca6
vpp[128]: #6  0x00007f95dfe7dca6 0x7f95dfe7dca6
vpp[128]: #7  0x00007f95def85770 0x7f95def85770
vpp[128]: #7  0x00007f95def85770 0x7f95def85770

**Comment by ondrej-fabry** [comment]
Please report this to VPP.
