### ISSUE TITLE
vpp crash when using vppagent 1.8

### ISSUE THREAD

**Issue by edwarnicke** [ligato/vpp-agent#1133]
We are seeing a [vpp crash in the logs](https://gist.github.com/edwarnicke/a4545938f1a6ccefb7042423badac6d1#file-vpp-crash-on-scale-in-nsm-log-L1542) as we try to scale test NSM.

Could you offer any insight or suggestions as to other information to gather (and how) so we can debug this issue?

We are seeing this at a scale of fewer than 10 'L2/L3 Connections', so the number of tapv2 interfaces is fairly small.

**Comment by edwarnicke** [comment]
@ondrej-fabry @VladoLavor Any ideas here?

**Comment by edwarnicke** [comment]
Some helpful links to assist in debugging @ondrej-fabry provided:

https://wiki.fd.io/view/VPP/BugReports#Core_Files

https://wiki.fd.io/view/VPP/BugReports#Binary_API_Trace

https://github.com/ligato/vpp-agent/blob/dev/docker/dev/README.md#running-vpp-in-debug-or-release-mode

**Comment by nickolaev** [comment]
That one can be close already. It is all fixed now that we use `2.x.x`.
