### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by sushsada** [ligato/vpp-agent#1139]
I see some tests defined here
https://github.com/ligato/vpp-agent/tree/master/tests/robot/suites

But I cant figure out how to run them. Could you provide an example?

Thanks.

**Comment by AndrejKilvady** [comment]
I did new wiki page:
https://github.com/ligato/vpp-agent/wiki/Run-tests
Do you need more information?

**Comment by sushsada** [comment]
@AndrejKilvady Thanks Andrej, but this link does not work. It takes me to "Create new page"

**Comment by AndrejKilvady** [comment]
sorry, something was changed:
https://github.com/ligato/vpp-agent/wiki/Tests-Locally

If the link will be changed again, I mean it will be still somewhere here on wiki:
https://github.com/ligato/vpp-agent/wiki

**Comment by sushsada** [comment]
Thanks for the quick help!

**Comment by ondrej-fabry** [comment]
A guide for running tests is available in Ligato Docs: http://docs.ligato.io/en/latest/testing/integration-tests/

Please open new issue if you encounter some problems.
