### ISSUE TITLE
Inconsistent Linux interface state after x-connection update

### ISSUE THREAD

**Issue by stepan-anokhin** [ligato/vpp-agent#1245]
## Description
We are observing inconsistent behavior of vpp-agent when trying to create and update cross-connection between two pods. We create and then update two x-connected kernel interfaces (src and dst) via grpc interface. Most of the times only one interface gets updated. The issue is intermittent. 

## Steps to reproduce
We have 3 pods: a dataplane (ligato/vpp-agent 1.8.1) and two alpine pods as peers (source-pod and destination-pod).

### Steps
1. [Create](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-request-first-txt-L1) a cross-connection between two pods ([agent logs](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-vpp-agent-logs-after-first-txt-L1))
2. Ping dest pod from source pod and vice-versa
3. [Update](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-request-second-txt-L1) a cross-connection: change interface name and ip address ([agent logs](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-vpp-agent-logs-after-second-txt-L1))
4. Ping dest pod from source pod and vice-versa

### Expected
At step 4 we expect source-pod and destination-pod to have **if2_src** and **if2_dst** interfaces respectively configured as specified in the [update](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-request-second-txt-L1) request. 

### Actual
Destination-pod has [if1_dst](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-ip-addr-dest-pod-txt-L7) interface with old ip address (as if step 3 was not executed at all). 

### Details
Here is some details collected after step 3:
Source-pod `ip addr` [output](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-ip-addr-source-pod-txt-L1).
Destination-pod `ip addr` [output](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-ip-addr-dest-pod-txt-L1)
Dataplane-pod `ip addr` [output](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-ip-addr-vpp-txt-L1)
Dataplane-pod `vppctl sh int` [output](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-vppctl-sh-int-after-second-txt-L1)

All requests are made via grpc `DataChangeService.Put` method
Vpp-agent version is 1.8.1

**Comment by VladoLavor** [comment]
@stepan-anokhin thanks for the detailed description. I tried the same setup several times but didn't hit such an issue myself. 

So if I understand it right, the problem you described is that the Linux tap **if1_dst** is not replaced properly with the updated **if2_dst**. In case the hostname was changed, the agent removes the old interface and configures it anew since the hostname cannot be directly rewritten. This makes sense with the update log:

```
time="2019-03-26 12:21:24.90351" level=info msg="Linux interface if1_dst removed" loc="ifplugin/interface_config.go(282)" logger=linux.if-conf
time="2019-03-26 12:21:24.95169" level=info msg="Linux interface DST-some-id with hostIfName if2_dst configured" loc="ifplugin/interface_config.go(173)" logger=linux.if-conf
```

If [this ](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-ip-addr-dest-pod-txt-L7)is the state of the `/proc/13418/ns/net` after the update, it means both operations quitely failed somehow... 

The log is at info-level with limited information, could you please provide a log at debug-level? You can set debug level with environment variable `INITIAL_LOGLVL=debug` for the agent.

**Comment by stepan-anokhin** [comment]
Hi @VladoLavor 

The issue is intermittent. I cannot reproduce it locally either. But on circle-ci it is observed in 4 out of 5 attempts. 

After I've added `INITIAL_LOGLVL=debug` the issue become unreproducible on circle-ci either. I'll provide logs when the issue will be observed again.

**Comment by stepan-anokhin** [comment]
Hi @VladoLavor 

The logs with debug-level could be found [here](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-all-logs-debug-enabled)

From logs I cant see that vpp-agent [unregisters](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-all-logs-debug-enabled-L216) **if1_dst** and then [registers](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-all-logs-debug-enabled-L233) it back again after the [update-request](https://gist.github.com/stepan-anokhin/de085ce503e012a43be5e9d7794d9d20#file-all-logs-debug-enabled-L127).

**Comment by ondrej-fabry** [comment]
Is this issue still relevant since you are in the process of migrating to v2? https://github.com/networkservicemesh/networkservicemesh/pull/867

**Comment by stepan-anokhin** [comment]
We will check if the issue is still reproducible on 2.0 and will let you know.
