### ISSUE TITLE
Enable IPv6 support when creating Linux interfaces

### ISSUE THREAD

**Issue by nickolaev** [ligato/vpp-agent#1308]
In `plugins/linux/ifplugin/descriptor/interface.go` method [`Create`](https://github.com/ligato/vpp-agent/blob/master/plugins/linux/ifplugin/descriptor/interface.go#L290) the ip addresses of the injected interfaces are set in this loop:
```go
	for _, ipAddress := range ipAddresses {
		err = d.ifHandler.AddInterfaceIP(hostName, ipAddress)
		// an attempt to add already assign IP is not considered as error
		if err != nil && syscall.EEXIST != err {
			err = errors.Errorf("failed to add IP address %v to linux interface %s: %v",
				ipAddress, linuxIf.Name, err)
			d.log.Error(err)
			return nil, err
		}
	}
```

However, due to https://github.com/containernetworking/cni/issues/531, it is impossible to set IPv6 addresses. The problem was solved for CNI in https://github.com/containernetworking/plugins/pull/113 for the IPAM CNI plugin. The essential code is here (https://github.com/containernetworking/plugins/blob/master/pkg/ipam/ipam_linux.go#L61):

```go
		// Make sure sysctl "disable_ipv6" is 0 if we are about to add
		// an IPv6 address to the interface
		if !has_enabled_ipv6 && ipc.Version == "6" {
			// Enabled IPv6 for loopback "lo" and the interface
			// being configured
			for _, iface := range [2]string{"lo", ifName} {
				ipv6SysctlValueName := fmt.Sprintf(DisableIPv6SysctlTemplate, iface)

				// Read current sysctl value
				value, err := sysctl.Sysctl(ipv6SysctlValueName)
				if err != nil || value == "0" {
					// FIXME: log warning if unable to read sysctl value
					continue
				}

				// Write sysctl to enable IPv6
				_, err = sysctl.Sysctl(ipv6SysctlValueName, "0")
				if err != nil {
					return fmt.Errorf("failed to enable IPv6 for interface %q (%s=%s): %v", iface, ipv6SysctlValueName, value, err)
				}
			}
			has_enabled_ipv6 = true
		}
```

The code is pretty straightforward and can be used as an inspiration to solve the problem with VPP-agent.

**Comment by ondrej-fabry** [comment]
PR #1317 should fix this, please test and close this.

**Comment by rdimitrov** [comment]
hey, @ondrej-fabry: Can you share a docker image that can be used for testing or should build it from scratch? Thanks! 👍

**Comment by ondrej-fabry** [comment]
Docker images are built from dev branch automatically,  see https://github.com/ligato/vpp-agent/blob/master/README.md#images

Just pull from `ligato/vpp-agent:dev`.

**Comment by rdimitrov** [comment]
Great, thanks! 👍

**Comment by rdimitrov** [comment]
hey, @ondrej-fabry. I've tested it and so far it looks great, thanks!  👍 
I'll keep an eye for when it gets merged

**Comment by ondrej-fabry** [comment]
Okay, I will close this for now. Release `v2.1.0` is planned for today, we're just finishing up. If you run into any other problems please open new issue.
