### ISSUE TITLE
No ABF in ConfigData

### ISSUE THREAD

**Issue by nickolaev** [ligato/vpp-agent#1354]
Although ABF is added in https://github.com/ligato/vpp-agent/blob/master/api/models/vpp/abf/abf.proto, there is no way to configure it through https://github.com/ligato/vpp-agent/blob/master/api/models/vpp/vpp.proto.

**Comment by VladoLavor** [comment]
Thanks for pointing it out, added in PR #1356.

**Comment by ondrej-fabry** [comment]
@nickolaev Just released [v2.1.1](https://github.com/ligato/vpp-agent/releases/tag/v2.1.1) which includes this fix.

**Comment by nickolaev** [comment]
@ondrej-fabry thanks. I have not tried it, but the patch looks OK. We can close this one.
