### ISSUE TITLE
API for SPAN

### ISSUE THREAD

**Issue by edwarnicke** [ligato/vpp-agent#1386]
I need vpp-agent to explose a grpc API for SPAN/RSPAN/ERSPAN.

**Comment by ondrej-fabry** [comment]
This is seems like new feature for vpp-agent.

I see this binary API for SPAN in span.api: https://github.com/FDio/vpp/blob/b7b929931a07fbb27b43d5cd105f366c3e29807e/src/vnet/span/span.api

For the others I have not found much.. there is ERSPAN mentioned in gre.api: https://github.com/FDio/vpp/blob/b7b929931a/src/vnet/gre/gre.api#L23

@edwarnicke could you please send some pointers for this as we have not used/configured this in VPP so far.

**Comment by edwarnicke** [comment]
Definitely a new feature.  After investigation I am breaking this issue up.  So for this one, we just need the SPAN API exposed.  Should be roughly the same complexity as the XCon API it looks like.

**Comment by edwarnicke** [comment]
[CLI command docs](https://docs.fd.io/vpp/19.04/clicmd_src_vnet_span.html)

**Comment by ondrej-fabry** [comment]
Implemented in #1430
