### ISSUE TITLE
API for VLXAN-GPE

### ISSUE THREAD

**Issue by edwarnicke** [ligato/vpp-agent#1388]
Network Service Mesh needs support for VXLAN-GPE in order to support pure L3 payloads.

VXLAN-GPE, in contrast to VXLAN, has a 'Next Protocol Field' allowing it to encap more than just an Ethernet frame, specifically it can encap and IP packet.

[VXLAN-GPE CLI docs](https://docs.fd.io/vpp/19.04/clicmd_src_vnet_vxlan-gpe.html) - note specifically the

```[next-ip4][next-ip6][next-ethernet][next-nsh]```

parameters that select the next protocol field value.

This corresponds to the [API field protocol](https://github.com/FDio/vpp/blob/b7b929931a07fbb27b43d5cd105f366c3e29807e/src/vnet/vxlan-gpe/vxlan_gpe.api#L28)

**Comment by rewenset** [comment]
Hi! I'm working on VXLAN-GPE feature for VPP-Agent and I want to ask one thing.
From reading this: 
https://github.com/FDio/vpp/blob/stable/1904/src/vnet/vxlan-gpe/decap.c#L86-L104
I've come to the conclusion that `decap_fib_id` (or `decap_vrf_id`) is used only when you set either `next-ip4` or `next-ip6` parameters. 
Can you please approve (or disapprove) this?

**Comment by edwarnicke** [comment]
I am not certain.  I can confirm that we want to be able to encap in VXLAN-GPE ethernet, IPv6, or IPv4.  In principle VXLAN-GPE could carry other protocols (though there is no implementation to do that currently), so when designing the GRPC API, you may want to be a bit more general.

**Comment by ondrej-fabry** [comment]
Implemented in #1457
