### ISSUE TITLE
configurator.ConfiguratorClient.Dump() returns error ' abfHandler is not available'

### ISSUE THREAD

**Issue by denis-tingajkin** [ligato/vpp-agent#1509]
Probably it is related to our vpp configuration,

## Steps to reproduce:

1) Use startup-config:  https://github.com/networkservicemesh/networkservicemesh/blob/master/dataplane/vppagent/conf/vpp/startup.conf
2) Create configurator.ConfiguratorClient with grpc connection via TCP localhost:9111
3) Do client.Update(someConfig)
4) Do client.Dump()

Expected: the client will return dump config 
Actual: the client returns an error `DumpAbfs failed: abfHandler is not available" loc="configurator/dump.go(66)`

## Full logs from pod with vpp-agent
[nsmd-dataplane-aks-nodepool1-25451877-vmss000000-vppagent-dataplane.log](https://github.com/ligato/vpp-agent/files/3703204/nsmd-dataplane-aks-nodepool1-25451877-vmss000000-vppagent-dataplane.log)

Take a look at line `time="2019-10-08 10:05:35.12662" level=error msg="DumpAbfs failed: abfHandler is not available" loc="configurator/dump.go(66)" logger=configurator.dump`

This logs line related to this code: https://github.com/networkservicemesh/networkservicemesh/blob/master/dataplane/sdk/vppagent/commit.go#L65

**Comment by rewenset** [comment]
Hello @denis-tingajkin 
I did look into this issue. The reason behind error with `DumpAbfs` is bug in the VPP Agent. But, the good news is that it was fixed already in newer releases of agent. So advice to fix this is to update agent to the latest version.

**Comment by denis-tingajkin** [comment]
@rewenset with version 2.3.0 problem is not reproducing. But I seem to me faced another problem. I'll report it as a separate issue.
