### ISSUE TITLE
Implement dump for linux plugins in configurator

### ISSUE THREAD

**Issue by ondrej-fabry** [ligato/vpp-agent#1528]
Currently configurator (api/configurator) service dumps only VPP related config. 

It uses vppcalls directly to dump, but linux has a lot of processing defined in KV descriptors. For this reason it might be neccessary to do dumps via KV scheduler. 

For consistency it would be good do the same for VPP related config and not use vppcalls directly. Possible implications should be understood first.

This needs to exist in some type of tests we have, probably as end-to-end tests.

**Comment by edwarnicke** [comment]
@ondrej-fabry ETA?

**Comment by VladoLavor** [comment]
@edwarnicke Linux dump is already implemented - at least I've tested Linux tap/veth interfaces - but it cannot be used with gRPC because of the reason @ondrej-fabry mentioned.

I'll have a look into this one.

**Comment by edwarnicke** [comment]
@denis-tingajkin looks like #1563 will be landing soon to fix this :)

**Comment by ondrej-fabry** [comment]
Fixed in #1563
