### ISSUE TITLE
NotifiyService sends empty statistics with vpp-agent v2.3.0 

### ISSUE THREAD

**Issue by denis-tingajkin** [ligato/vpp-agent#1537]
Looks like https://github.com/ligato/vpp-agent/blob/master/plugins/configurator/notify.go#L30 with vpp-agent 2.3.0 sends empty statistics.

### Steps to reproduce:

1) Use Supervisor.conf (see below)
2) Use vpp.conf (see below)
3) Create configurator client and connect to configurator service via tcp localhost:9111
4) Subscribe on notification as in examples https://github.com/ligato/vpp-agent/blob/master/examples/grpc_vpp/notifications/main.go#L83 / using MetricsCollector (see below)
5) Call configurator.Client.Update wtih config: 
```
vpp_config:<interfaces:<name:\"SRC-1\" type:TAP enabled:true tap:<version:2 > > interfaces:<name:\"DST-1\" type:VXLAN_TUNNEL enabled:true vxlan:<src_address:\"172.28.128.35\" dst_address:\"172.28.128.36\" vni:2 > > xconnect_pairs:<receive_interface:\"SRC-1\" transmit_interface:\"DST-1\" > xconnect_pairs:<receive_interface:\"DST-1\" transmit_interface:\"SRC-1\" > > linux_config:<interfaces:<name:\"SRC-1\" type:TAP_TO_VPP namespace:<type:FD reference:\"/proc/28253/ns/net\" > host_if_name:\"nsm0\" enabled:true ip_addresses:\"172.16.1.1/30\" tap:<vpp_tap_if_name:\"SRC-1\" > > routes:<outgoing_interface:\"SRC-1\" scope:GLOBAL dst_network:\"8.8.8.8/30\" gw_addr:\"172.16.1.2\" > > " operation="*commit.Request
```
6) Do ping from SRC interface to DST interface
7) Kill container with SRC interface / Call configurator.Client.Delete with config
```
vpp_config:<interfaces:<name:\"SRC-1\" type:TAP enabled:true tap:<version:2 > > interfaces:<name:\"DST-1\" type:VXLAN_TUNNEL enabled:true vxlan:<src_address:\"172.28.128.35\" dst_address:\"172.28.128.36\" vni:2 > > xconnect_pairs:<receive_interface:\"SRC-1\" transmit_interface:\"DST-1\" > xconnect_pairs:<receive_interface:\"DST-1\" transmit_interface:\"SRC-1\" > > linux_config:<interfaces:<name:\"SRC-1\" type:TAP_TO_VPP namespace:<type:FD > host_if_name:\"nsm0\" enabled:true ip_addresses:\"172.16.1.1/30\" tap:<vpp_tap_if_name:\"SRC-1\" > > routes:<outgoing_interface:\"SRC-1\" scope:GLOBAL dst_network:\"8.8.8.8/30\" gw_addr:\"172.16.1.2\" > > 
```
8) Get notification from notification client (from step 4)
```
new statistics vpp_notification: <\n  interface: <\n    state: <\n      name: \"SRC-1\"\n      internal_name: \"tap0\"\n      if_index: 3\n      admin_status: DELETED\n      oper_status: DELETED\n      last_change: 1571814862\n      phys_address: \"02:fe:d0:fd:bd:49\"\n      mtu: 9216\n      statistics: <\n      >\n    >\n  >\n>\n"
```

**Actual:** statistics are empty
**Expected:** statistics are not empty

### Context

[Supervisor.conf](https://github.com/networkservicemesh/networkservicemesh/blob/master/forwarder/vppagent/conf/supervisord/supervisord.conf)
[vpp.conf](https://github.com/networkservicemesh/networkservicemesh/blob/master/forwarder/vppagent/conf/vpp/startup.conf)
[Metrics collector](https://github.com/networkservicemesh/networkservicemesh/blob/master/forwarder/vppagent/pkg/vppagent/metrics_collector.go)

#### Logs from the container with vpp-agent v2.3.0:
[nsmd-forwarder-kube-master-vppagent-forwarder.log](https://github.com/ligato/vpp-agent/files/3760824/nsmd-forwarder-kube-master-vppagent-forwarder.log)

#### Logs from the container with vpp-agent v2.1.1:
[nsmd-forwarder-kube-master-vppagent-forwarder.log](https://github.com/ligato/vpp-agent/files/3760794/nsmd-forwarder-kube-master-vppagent-forwarder.log)

Notice: Result of step 8, statistics are not empty:
```
vpp_notification: <\n  interface: <\n    type: UPDOWN\n    state: <\n      name: \"SRC-1\"\n      internal_name: \"tap0\"\n      if_index: 3\n      admin_status: DELETED\n      oper_status: DELETED\n      last_change: 1571813808\n      phys_address: \"02:fe:9e:f2:db:f3\"\n      mtu: 9216\n      statistics: <\n        in_packets: 6\n        in_bytes: 476\n        out_packets: 6\n        out_bytes: 476\n      >\n    >\n  >\n>\n
```

**Comment by edwarnicke** [comment]
@ondrej-fabry Could you have a look at this?

**Comment by denis-tingajkin** [comment]
@edwarnicke I just found that our vpp.cnf is not using by vpp... Looks like it is related to this https://github.com/networkservicemesh/networkservicemesh/commit/f8504286ebf6bfae48f166908eb918298d745def#diff-9ff428908811536f7936f7e23679ac7dL1-R15

**Comment by VladoLavor** [comment]
@denis-tingajkin 
Notifications are related to the interface state change events - the change event contains interface name, index, and flags (admin/oper status) but no statistics. However, the agent fills up other interface data including statistics from the local cache - if there are any.

On the other side, statistics are periodically polled every 5 seconds (this is currently not configurable). Read data are internally stored, but the change in statistics does not generate a notification.

What I want to say is that state notifications and interface counters are handled independently - if an interface is created and removed within polling timeout, counters will be empty just because they were not read yet. This was the only way so far I managed to get empty statistics upon deletion.

However, from the provided log I cannot say for sure that this is the case. Can you please try the same thing with vpp-agent 2.3.0, giving it a bit more time between interface update/delete? Also, set the variable `DEBUG_IFSTATES` - it provides some more logs to look at.

**Comment by denis-tingajkin** [comment]
fixed by https://github.com/ligato/vpp-agent/issues/1543#issuecomment-546236980
