### ISSUE TITLE
StatsPollerService doesn't send anything with vpp-agent v2.3.1

### ISSUE THREAD

**Issue by denis-tingajkin** [ligato/vpp-agent#1538]
I trying to use https://github.com/ligato/vpp-agent/blob/32d51178c3be100b443283b2f2501929c77830d5/plugins/telemetry/stats_poller.go#L19, instead of https://github.com/ligato/vpp-agent/blob/32d51178c3be100b443283b2f2501929c77830d5/plugins/configurator/notify.go#L30
But it did not send anything.

### Steps to reproduce:
1) Use [vpp.conf](https://github.com/networkservicemesh/networkservicemesh/blob/master/forwarder/vppagent/conf/vpp/startup.conf)
2) Use [supervisor.conf](https://github.com/networkservicemesh/networkservicemesh/blob/master/forwarder/vppagent/conf/supervisord/supervisord.conf)
3) Use [telemetry.conf](https://github.com/networkservicemesh/networkservicemesh/pull/1802/files#diff-9d6845fdafedcd41c83211421121a017R1)
4) Create configurator.ConfiguratorClient with grpc connection via TCP localhost:9111
5) Start poll stats client as in example https://github.com/ligato/vpp-agent/blob/32d51178c3be100b443283b2f2501929c77830d5/examples/grpc_vpp/stats_poller/main.go#L71 / Using similar implementation https://github.com/networkservicemesh/networkservicemesh/pull/1802/files#diff-ca0cc2f27eee1bbe02f447ae8f25f814L1
6) Call client.Update(config) where config is 
```
vpp_config: <
  interfaces: <
    name: "SRC-1"
    type: TAP
    enabled: true
    tap: <
      version: 2
    >
  >
  interfaces: <
    name: "DST-1"
    type: TAP
    enabled: true
    tap: <
      version: 2
    >
  >
  xconnect_pairs: <
    receive_interface: "SRC-1"
    transmit_interface: "DST-1"
  >
  xconnect_pairs: <
    receive_interface: "DST-1"
    transmit_interface: "SRC-1"
  >
>
linux_config: <
  interfaces: <
    name: "SRC-1"
    type: TAP_TO_VPP
    namespace: <
      type: FD
      reference: "/proc/7477/ns/net"
    >
    host_if_name: "nsm0"
    enabled: true
    ip_addresses: "172.16.1.1/30"
    tap: <
      vpp_tap_if_name: "SRC-1"
    >
  >
  interfaces: <
    name: "DST-1"
    type: TAP_TO_VPP
    namespace: <
      type: FD
      reference: "/proc/7192/ns/net"
    >
    host_if_name: "nsm9QjSeyg9"
    enabled: true
    ip_addresses: "172.16.1.2/30"
    phys_address: "2a:42:a5:73:90:97"
    tap: <
      vpp_tap_if_name: "DST-1"
    >
  >
  routes: <
    outgoing_interface: "SRC-1"
    scope: GLOBAL
    dst_network: "8.8.8.8/30"
    gw_addr: "172.16.1.2"
  >
>
```
7) Do few pings from SRC interface to DST interface
8) Kill container with SRC inteface / call client.Delete

**Expected:** poll stats client received something.
**Actual:** poll stats client received nothing.

### Logs
[nsmd-forwarder-ip-192-168-150-79.us-east-2.compute.internal-vppagent-forwarder.log](https://github.com/ligato/vpp-agent/files/3761597/nsmd-forwarder-ip-192-168-150-79.us-east-2.compute.internal-vppagent-forwarder.log)

### PR
https://github.com/networkservicemesh/networkservicemesh/pull/1802

**Comment by denis-tingajkin** [comment]
also reproduced with vpp-agent v2.4.0

**Comment by ondrej-fabry** [comment]
You seem to not have Stats API enabled in VPP.

I see this in your log: 

```
------------------------------------------------------------
 VPP stats socket file /run/vpp/stats.sock is missing!

  - is VPP running with stats segment enabled?
  - is the correct socket name configured?

 To enable it add following section to your VPP config:
   statseg {
     default
   }
------------------------------------------------------------
time="2019-10-23 08:22:35.88846" level=warning msg="Unable to connect to the VPP statistics socket, stats socket file /run/vpp/stats.sock does not exist" loc="govppmux/plugin_impl_govppmux.go(160)" logger=govpp
```

**Comment by denis-tingajkin** [comment]
@ondrej-fabry probably I tried did it locally, let me check on CI https://github.com/networkservicemesh/networkservicemesh/pull/1802/commits/2f3446b12ccf3338111256679283c4413aadfa5a

**Comment by denis-tingajkin** [comment]
@ondrej-fabry even with this change networkservicemesh/networkservicemesh@2f3446b I found in logs this
```
------------------------------------------------------------
 VPP stats socket file /run/vpp/stats.sock is missing!

  - is VPP running with stats segment enabled?
  - is the correct socket name configured?

 To enable it add following section to your VPP config:
   statseg {
     default
   }
------------------------------------------------------------
```
Do you have any idea?

**Comment by ondrej-fabry** [comment]
Did you check the file? Is it really there? Is the stats API accessible? Run `vpp_get_stats ls /sys/`.

**Comment by denis-tingajkin** [comment]
Yes, I did and it there.

Also, you can see it in attached logs
```
time="2019-10-23 11:20:39.43105" level=debug msg="vpp# show version cmdline:\nCommand line arguments:    /usr/bin/vpp  unix    {    nodaemon    log    /var/log/vpp/vpp.log    full-coredump    cli-listen    /run/vpp/cli.sock    gid    vpp    poll-sleep-usec    1000    }  statseg    {    default    }  api-trace    {    on    }  api-segment    {    gid    vpp    }  socksvr    {    default    }  cpu    {    }  plugins    {    plugin    dpdk_plugin.so      {      disable      }    }" loc="govppmux/plugin_impl_govppmux.go(233)" logger=govpp
```

**Comment by denis-tingajkin** [comment]
$ vpp_get_stats
```
Couldn't connect to vpp, does /run/vpp/stats.sock exist?
```
$ ls /sys/ 
```
block  class  devices	fs	    kernel  power
bus    dev    firmware	hypervisor  module
```

**Comment by denis-tingajkin** [comment]
@ondrej-fabry I've found a pure case to reproduce a problem with message about `statseg`.
Steps:
1) Create dockerfile
```
FROM ligato/vpp-agent:v2.3.0 as runtime
RUN rm /opt/vpp-agent/dev/etcd.conf; 

```
2) Build image
```
docker build -t test:v1 .
```
3) Run  `docker run -ti test:v1 cat /etc/vpp/vpp.conf` and make sure `statseg`, `socksvr` are passed.
4) Run `docker run -ti vpp-agent-init`

Actual:
```
------------------------------------------------------------
 VPP stats socket file /run/vpp/stats.sock is missing!

  - is VPP running with stats segment enabled?
  - is the correct socket name configured?

 To enable it add following section to your VPP config:
   statseg {
     default
   }
------------------------------------------------------------
```

**Comment by denis-tingajkin** [comment]
@ondrej-fabry did I miss something?

**Comment by denis-tingajkin** [comment]
StatsPollerService sends statistics.

But statistics have strange interface names. 
I'll create another issue for this.
