### ISSUE TITLE
Downstream resync cause SIGSEGV in vpp sr policy

### ISSUE THREAD

**Issue by artem-belov** [ligato/vpp-agent#1566]
## Current Behavior

When creating sr policy, vpp creates vrf-table with id 4294967295. Next time when calling Downstream Resync vpp-agent removes this vrf-table which cause SIGSEGV fault in next vpp calls.

>  2. DELETE [DISCOVERED]:
>           - key: config/vpp/v2/vrf-table/id/4294967295/protocol/IPV6
>           - value: { id:4294967295 protocol:IPV6 label:"SRv6 steering of IP6 prefixes through BSIDs"  } 

## Expected Behavior

Vpp-agent should not remove this vrf-table.

As temporary fix I am creating similar vrf-table via api:

```
rv.VppConfig.Vrfs = []* vpp_l3.VrfTable{
	{
		Id:                   math.MaxUint32,
		Protocol:             vpp_l3.VrfTable_IPV6,
		Label:                "SRv6 steering of IP6 prefixes through BSIDs",
	},
}
```

## Steps to Reproduce

1. Create sr policy
2. Call downstream resync
3. Try to create another sr policy

## Context

* vpp-agent 2.3.0
* vpp 19.08

## Failure Logs

[srv6-error.log](https://github.com/ligato/vpp-agent/files/3858130/srv6-error.log)

**Comment by ondrej-fabry** [comment]
Possible solution: the vrf-table descriptor should recognize this specific ID=MaxUint32 as origin=fromSB to avoid removing it. 

https://github.com/EMnify/vpp-agent/blob/38820fce174a52ee18a387632356bb5cbcea9220/plugins/vpp/l3plugin/descriptor/vrf_table.go#L143-L145

Basically the if condition above, should be changed to something like:

```go
if table.Id > 0 && table.Id < math.MaxUint32 {
    origin = kvs.FromNB
}
```

CC @milanlenco

**Comment by milanlenco** [comment]
Sorry for the late response, somehow I have missed this thread...
Anyway, the solution proposed by Ondrej seems to me like a good one, cannot think of any negative consequences, so feel free to create a PR.
