### ISSUE TITLE
Upgrade to protoc-gen-go v1.3.3 and use grpc.ClientConnInterface

### ISSUE THREAD

**Issue by edwarnicke** [ligato/vpp-agent#1612]
proto-gen-go v1.3.3 switches over from using *grpc.ClientConn (a struct) tto grpc.ClientConnInterface.

This allows us to Mock grpc.ClientConnInterface for unit testing.

In order for Network Service Mesh to complete this transition, we need configurator.NewConfiguratorClient to accept grpc.ClientConnInterface instead of *grpc.ClientConn

Upgrading to proto-gen-go v1.33 and rerunning go generate should do it :)

Please also note, this is completely backward compatible, as *grpc.ClientConn meets the grpc.ClientConnInterface.

**Comment by ondrej-fabry** [comment]
Done
