### ISSUE TITLE
Will vpp-agent support vpp 20.05 and if so, when? Or is it possible already now?

### ISSUE THREAD

**Issue by eliasrudberg** [ligato/vpp-agent#1647]
We have been using vpp-agent for a while with vpp 19.08 which has been working fine. Now we are preparing to switch to the most recent vpp version (current vpp master branch, soon the upcoming 20.05 release). See https://wiki.fd.io/view/Projects/vpp/Release_Plans/Release_Plan_20.05 for the vpp 20.05 release plan.

Will vpp-agent support vpp 20.05 and if so, when?

Is it possible to make it work with vpp 20.05 (current vpp master branch) already now and if so, how can we do that?

**Comment by ondrej-fabry** [comment]
Run `make images VPP_VERSION=2005` to build images for VPP 20.05.
