### ISSUE TITLE
Migrate Travis CI from ".org" to ".com"

### ISSUE THREAD

**Issue by odidev** [ligato/vpp-agent#1737]
Hi,
I was trying to add arm64 jobs for travis-CI, but it is failing. As this project uses lxd containers for testing and arm64 is already built over the unprivileged lxd containers and to implement nested container concept we must have privileged lxd containers. Due to this reason the tests are failing for **arm64**. This issue can be solved if we use **arm64-graviton2**.

As per https://blog.travis-ci.com/2020-09-11-arm-on-aws the arm64-graviton support is added for travis-ci.com. I have tested the package successfully over arm64-graviton. Please find the link below:

https://travis-ci.com/github/odidev/vpp-agent/builds/188559357

It will be very helpful for arm64 users, if we migrate this project from **travis-ci.org** to **travis-ci.com**.
Please let me know if any help is required.

**Comment by ondrej-fabry** [comment]
We already migrated to travis-ci.com a long time ago, actually very soon after it was publicly available. The repo would not be available there if we did not: https://travis-ci.com/github/ligato/vpp-agent

Why do you assume we have not migrated yet?
