### ISSUE TITLE
Add support for setting values for custom models using agentctl

### ISSUE THREAD

**Issue by fgschwan** [ligato/vpp-agent#1740]
## Problem

When 3rd party registers custom proto models (for 3rd party plugins), they have not the ability to use `Configurator` service (or `agentctl config`) to configure the agent remotely. 

This is because the [`ConfiguratorService`](https://github.com/ligato/vpp-agent/blob/master/proto/ligato/configurator/configurator.proto#L91) uses pre-defined proto message [`Config`](https://github.com/ligato/vpp-agent/blob/master/proto/ligato/configurator/configurator.proto#L12) for retrieving or modifyng the configuration and it contains only configuration(models) in the official vpp-agent. For it to be able to use it for custom models, users would need to edit the proto file definition which could only be done via forking the vpp-agent repo which is not maintainable. 

## Solution

Agentctl [uses](https://github.com/ligato/vpp-agent/blob/0ead9d2f79c84a9bfe2e54794806c015ded188f3/cmd/agentctl/commands/config.go#L148) non-generic configurator. We should change it to [generic client configurator](https://github.com/ligato/vpp-agent/blob/0ead9d2f79c84a9bfe2e54794806c015ded188f3/client/client_api.go#L34) that could use its [known models](https://github.com/ligato/vpp-agent/blob/0ead9d2f79c84a9bfe2e54794806c015ded188f3/client/client_api.go#L36) method from API that contains also 3rd party models (they are registered). Then transform the models into proto-generated go structures(using [dynamic](https://pkg.go.dev/github.com/jhump/protoreflect/dynamic) tool) that can be used with generic configuration client (see [example](https://github.com/ligato/vpp-agent/blob/0ead9d2f79c84a9bfe2e54794806c015ded188f3/examples/customize/custom_api_model/main.go#L187-L193)) to configure it the same way as before but with 3rd party models. We need also write conversion in opposite direction (proto-generated go struct to model from known models) to replace configuration client in whole agentctl's config submodule.

### Considered Alternatives

* Add repeated `google.proto.Any` field to the `Config` message in the configurator.proto model that could contain 3rp party custom models
  Problems with supporting 2 ways how to configure data, mixing dynamic/static configuration (possible setting of static part in with dynamic configuration=problem), it doesn't solve future additions in existing configurations (for agentctl yaml config update)

**Comment by ondrej-fabry** [comment]
Fixed in #1754
