### ISSUE TITLE
There are two VPP running together with  one VPP agent

### ISSUE THREAD

**Issue by wxxxx123456** [ligato/vpp-agent#1752]
In my environment 
There are two VPP running together with the  one VPP agent；
I want that，one vpp-agent can control all vpp.

i read the doc https://docs.ligato.io/en/latest/plugins/vpp-plugins/#govppmux-plugin

`The default behaviour assumes that there is only a single VPP running in an environment together with the VPP agent. In the case where VPP runs with a customized SHM prefix, or there are several VPP instances running side-by-side, GoVPP must know the SHM prefix in order to connect to the desired VPP instance. The prefix must be included in the GoVPPMux conf file, with the key shm-prefix, and the value matching the VPP shared memory prefix name.`

so .I edited the govpp.conf this
```
binapi-socket-path:  
 - /run/vpp/capi.sock #vpp2
 - /run/vpp/api.sock  # vpp1
```
```
log 
 level=fatal msg="1 error(s) decoding:\n\n* 'binapi-socket-path' expected type                                                                                                'string', got unconvertible type '[]interface {}'" loc="vpp-agent/main.go(87)" logger=defaultLogger
```

but not useful,what should i do.

**Comment by ondrej-fabry** [comment]
There is no support for multiple VPP instances being managed by a single vpp-agent. The documentation mentions multiple VPPs running, but that is not for a single vpp-agent.


The `binapi-socket-path` is a string not a string list:

```go
//...
BinAPISocketPath string `json:"binapi-socket-path"`
/...
```
> https://github.com/ligato/vpp-agent/blob/master/plugins/govppmux/config.go#L35

That's why you are getting error.

**Comment by wxxxx123456** [comment]
Thx.I already read code。:-))
