### ISSUE TITLE
VPP default version in v3.2.0

### ISSUE THREAD

**Issue by glazychev-art** [ligato/vpp-agent#1759]
Thanks for v3.2.0 release!
I see that it is using VPP v20.05 by default.
But v3.2.0 is also support newer VPP v20.09.
Are you planning to change the default version?

**Comment by ondrej-fabry** [comment]
Have not planned any specific timeframe. If you want to build agent with different VPP version run `make images VPP_VERSION=2009`.

**Comment by glazychev-art** [comment]
Thank you.
