### ISSUE TITLE
make test fails with integration tests failures(although only unit test must be ran) on 3.0.1

### ISSUE THREAD

**Issue by oicnysa** [ligato/vpp-agent#1771]
Hi, need you advice.
I've written some unit tests for my plugin. Running make test target to run them and everything is fine, despite the fact that it tries also to execute integration and e2e tests, which of course fails as they're expected to be executed by another targets.
There is no such problem on master. Maybe you could advice how it may be fixed?

**Comment by ondrej-fabry** [comment]
This was fixed in latest version, hence why it does not cause issue on master.
