### ISSUE TITLE
How to use shared memory 

### ISSUE THREAD

**Issue by oicnysa** [ligato/vpp-agent#1802]
I've been trying to use shared memory with vpp-agent, but have got an error message like:
```
Using shared memory for VPP binary API is not currently supported in pure Go client!

To use socket client for VPP binary API (recommended):

    unset GOVPPMUX_NOSOCK environment variable

    remove these settings from govpp.conf config: shm-prefix, connect-via-shm

If you still want to use shared memory for VPP binary API:

    compile your agent with this build tag: vppapiclient

    vppapiclient requires CGo and needs VPP to be installed
    panic: No implementation for shared memory in pure Go client!
```

I found two vppapiclient tags in adapter_puregoclient.go and adapter_vppapiclient.go
In adapter_puregoclient.go it is disabled, so I have enabled it, but when building vpp-agent got an error message like:
```
plugins/govppmux/plugin_impl_govppmux.go:118:16: undefined: NewVppAdapter
plugins/govppmux/plugin_impl_govppmux.go:151:18: undefined: NewStatsAdapter
plugins/govppmux/plugin_impl_govppmux.go:165:23: undefined: NewVppAdapter
plugins/govppmux/plugin_impl_govppmux.go:165:55: undefined: NewStatsAdapter
```

So can't really understand, where I need to define vppapiclient tag, to build vpp-agent with shared memory and if this even possible?

**Comment by ondrej-fabry** [comment]
The vppapiclient is deprecated and not maintained anymore. It is recommended to use statsclient/socketclient for communication with VPP as it is much faster without overhead of CGo and actively maintained. 
Is there any specific reason you require vppapiclient?

**Comment by chrismetz09** [comment]
Okay to include note at https://github.com/ligato/vpp-agent/blob/bd7edfd0f8e31af506a5b3a72623de62d5944da1/plugins/govppmux/adapter_puregoclient.go#L28 in the relevant locations in docs?

**Comment by oicnysa** [comment]
@ondrej-fabry now. I've just observed that vpp+vpp-agent is performing, when processing API messages(stucks at some point and then goes again). Wanted to check that maybe shared memory could resolve the problem, but unfortunately it doesn't resolve my problems.

**Comment by ondrej-fabry** [comment]
> 
> 
> @ondrej-fabry no. I've just observed that vpp+vpp-agent is performing badly, when processing API messages(stucks at some point and then goes again). Wanted to check that maybe shared memory could resolve the problem, but unfortunately it doesn't resolve my problems.

Could you open issue for this problem? Ideally with logs and some context info.

**Comment by oicnysa** [comment]
Well I've just switched from fluentd log driver to syslog log driver.
