### ISSUE TITLE
Is there any plan about supporting VPP 22.06 or 22.10?

### ISSUE THREAD

**Issue by WentianBu** [ligato/vpp-agent#1882]
I am using linux-cp and linux-nl plugin in VPP 22.06, however the ligato vpp-agent 3.4.0 only supports VPP 22.02. Is there any plan about supporting VPP 22.06 or 22.10 in the future? Or what should I do to manually make current vpp-agent work with VPP 22.06?

**Comment by ondrej-fabry** [comment]
I think adding support for VPP 22.10 will be backwards compatible with 22.06.
