### ISSUE TITLE
message acl_add_replace with CRC 3c317936 is not compatible with the VPP we are connected to

### ISSUE THREAD

**Issue by remip2** [ligato/vpp-agent#242]
Hi,

I'm trying to use the framework with k8s based on the perf-demo code. If I try to add an ip address to a port of the VNF:

```
/vnf-agent/vnf1/vpp/config/v1/interface/port1
{"name":"port1","type":2,"enabled":true,"mtu":1500,"memif":{"id":1,"socket_filename":"/tmp/memif.sock"},"ip_addresses":["192.168.0.254/24"]}
```

I get this error from vpp-agent: 

```
time="2017-11-13 12:57:08.01573" level=error msg="unable to retrieve message ID: unkonwn message" msg_crc=3c317936 msg_name="acl_add_replace"
time="2017-11-13 12:57:08.01576" level=error msg="message acl_add_replace with CRC 3c317936 is not compatible with the VPP we are connected to" loc="vppcalls/compatibility_check_vppcalls.go(47)" logger=default-plugins-acl-plugin tag=00000000
time="2017-11-13 12:57:08.01579" level=error msg="plugin VPP: Init error 'message acl_add_replace with CRC 3c317936 is not compatible with the VPP we are connected to', took 498.31µs" durationInNs=498310 loc="core/agent_core.go(206)" logger=defaultLogger tag=00000000
```

I'm using the docker hub ligato/vpp-agent:latest image.

Do you know why the binary api is not synced with the vpp included in the image ?

**Comment by msestak77** [comment]
Hi,
please provide full vpp_agent log. How old is your image? please run "docker images" to check how old is your local image. Is this error message generated after you try tu put /vnf-agent/vnf1/vpp/config/v1/interface/port1
{"name":"port1","type":2,"enabled":true,"mtu":1500,"memif":{"id":1,"socket_filename":"/tmp/memif.sock"},"ip_addresses":["192.168.0.254/24"]}   o r is it in the log already? Theoretically if there is missmatch of versions, this error should happen for every call

**Comment by remip2** [comment]
my bad, I deleted all my local images to be sure to get the latest version and everything is working now.
