### ISSUE TITLE
Using the RestAPI

### ISSUE THREAD

**Issue by johnpearson555** [ligato/vpp-agent#345]
Is there a way to use the Rest API separately without the full agent? I'd like to run it to interface with my vanilla VPP installation. 

Thanks for open-sourcing btw.

**Comment by jmedved** [comment]
Yes. But you probably need to write some glue code, depending on what you want or do not want to include in your custom agent.

The agent is modular – it’s basically a set of plugins. All functionality is implemented as plugins and you only include those plugins that you really want to use in your app. To do that, you create your own VPP Agent flavor that contains the desired set of plugins. I guess in your case you would use the cn-infra plugins like the logger, the HTTP mux, maybe the health check, … and you would add your own rest_plugin on top of that.

Adding your own REST plugin is quite easy. Just clone the vpp/plugins/restplugin plugin and throw out all handlers in rest_handlers.go except for the last one - showCommandHandler(). This handler uses GoVPP directly and invokes VPP show command functions. The other handlers in rest_handlers.go use other VPP agent plugin APIs (l2, L3, ACL, …) - if you use rest_plugin unmodified, those other plugins will get pulled into your executable, even if you do not use them in your code.

Anyway, showCommandHandler() is a good example how to use GoVPP from REST handlers and how to interact with VPP directly. If the generic show function implemented in showCommandHandler() is not enough, you would have to write your own REST handlers (e.g. for configuration or for dumping information or whatever you want to do) using the same basic pattern found in this handler.

Please let us know if you have any questions about the above.


/Jan

**Comment by johnpearson555** [comment]
Thanks for the quick response.

So just to make sure I understand correctly:
- I should modify rest_handlers.go to only have the showCommandHandler function. Should I do this even if I want the the ACL and fib info through the REST interface?
- Implement a flavor with logger and http mux to start. Do I need the GoVPP plugin?
- What do I set f.RESTAPIPlugin.Deps.PluginInfraDeps & f.RESTAPIPlugin.Deps.HTTPHandlers to?

**Comment by ondrej-fabry** [comment]
Closing due age.
