### ISSUE TITLE
Running vppagent and vpp through Supervisord resulting in goVPP timeout error

### ISSUE THREAD

**Issue by swatisehgal** [ligato/vpp-agent#442]
Hi, I am trying to run the vpp agent k8s setup explained [here](https://github.com/ligato/vpp-agent/tree/master/k8s/dev-setup). I am facing issues running vpp and vpp-agent through supervisord and getting the following error:  **Error loading core: plugin GoVPP not completed before timeout**. However, when I run both vpp and vpp agent manually, it runs okay. Can you please let me know if there is something in supervisord configuration that needs to be changed to get this running.

**Comment by ondrej-fabry** [comment]
What image are you using? Did you built it yourself? Try changing the [used image in .yaml file](https://github.com/ligato/vpp-agent/blob/master/k8s/dev-setup/vnf-vpp.yaml#L39) for example to the official production image: `ligato/vpp-agent`.

**Comment by ondrej-fabry** [comment]
Closing due age. Please open new issue if you run into some problem again.
