### ISSUE TITLE
Issues in running Performance demo Scenario 2 and Scenario 4

### ISSUE THREAD

**Issue by swatisehgal** [ligato/vpp-agent#455]
I am successfully able to run Scenario 1 in the performance demo without any issues. However, when I try to run Scenario 2 and Scenario 4, I see the following issues:

1. Scenario 2:

- When I telnet into the vswitch, and run _**show int**_ the NIC interfaces are not visible and I only see the four memif interfaces. I double checked the interface names in the file scenario4/etcd.txt and also deleted the etcd pod and recreated it to ensure that the etcd configuration from the scenario 1 is completely deleted.

- Both the VNFs show two memif interfaces each which is the expected behavior 

1. Scenario 4

- On the vswitch I see host-vnf1_port1 and host-vnf1_port2 but dont see any interfaces on the vnf

Any idea where I am going wrong? I have followed exactly the same steps for scenario 1 and got it working but don't see the expected behavior for the other two scenarios.

**Comment by swatisehgal** [comment]
Got scenario 2 working. I had missed updating the pci addresses in the vswitch vpp configuration config map. Still didn't issues with scenario4 though.

**Comment by swatisehgal** [comment]
There is a bug in the scenario4 etcd.txt file. I had to make a few changes to get that working. Will submit a patch soon.

**Comment by ondrej-fabry** [comment]
Closing due age. Please open new issue if needed.
