### ISSUE TITLE
VPP received SIGBUS while running k8s/perf-demo/ scenarios in VM

### ISSUE THREAD

**Issue by saurabhjain06** [ligato/vpp-agent#621]
Hi,

I am using VMWare VM to bring up the scenario4 of VPP agent.
I followed all the steps that are given in README.md, but I am getting below error:

> 2018-05-18 17:24:01,048 DEBG 'vpp' stdout output:
> load_one_plugin:184: Loaded plugin: kubeproxy_plugin.so (kube-proxy data plane)
> 
> 2018-05-18 17:24:01,048 DEBG 'agent' stdout output:
> time="2018-05-18 17:24:01.04781" level=info msg="plugin PrometheusRPC: Init took 219.266µs" durationInNs=219266 loc="core/agent_core.go(295)" logger=agentcore
> time="2018-05-18 17:24:01.04792" level=info msg="plugin GRPC: Init took 77.503µs" durationInNs=77503 loc="core/agent_core.go(295)" logger=agentcore
> time="2018-05-18 17:24:01.04800" level=info msg="plugin IfStatePub: Init took 401ns" durationInNs=401 loc="core/agent_core.go(295)" logger=agentcore
> 
> 2018-05-18 17:24:01,048 DEBG 'vpp' stdout output:
> load_one_plugin:184: Loaded plugin: l2e_plugin.so (L2 Emulation)
> load_one_plugin:184: Loaded plugin: lb_plugin.so (Load Balancer)
> 
> 2018-05-18 17:24:01,048 DEBG 'vpp' stdout output:
> load_one_plugin:184: Loaded plugin: libsixrd_plugin.so (IPv6 Rapid Deployment on IPv4 Infrastructure (RFC5969))
> load_one_plugin:184: Loaded plugin: memif_plugin.so (Packet Memory Interface (experimetal))
> 
> 2018-05-18 17:24:01,049 DEBG 'vpp' stdout output:
> load_one_plugin:184: Loaded plugin: nat_plugin.so (Network Address Translation)
> 
> 2018-05-18 17:24:01,049 DEBG 'vpp' stdout output:
> load_one_plugin:184: Loaded plugin: pppoe_plugin.so (PPPoE)
> 
> 2018-05-18 17:24:01,050 DEBG 'vpp' stdout output:
> load_one_plugin:184: Loaded plugin: stn_plugin.so (VPP Steals the NIC for Container integration)
> 
> 2018-05-18 17:24:01,068 DEBG 'vpp' stdout output:
> /usr/bin/vpp[12]: unix_physmem_region_alloc:231: physmem page for region 'buffers' allocated on the wrong numa node (requested 0 actual 4294967294)
> 
> 2018-05-18 17:24:01,068 DEBG 'vpp' stdout output:
> /usr/bin/vpp[12]: received signal SIGBUS, PC 0x7f9ad03b7a5e
> 
> 2018-05-18 17:24:01,241 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 139955335379352 for <Subprocess at 139955336328472 with name vpp in state STARTING> (stdout)>
> 2018-05-18 17:24:01,241 INFO exited: vpp (terminated by SIGABRT (core dumped); not expected)
> 2018-05-18 17:24:01,241 DEBG received SIGCLD indicating a child quit
> 2018-05-18 17:24:02,243 INFO success: vpp_or_agent_not_running entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2018-05-18 17:24:02,245 INFO spawned: 'vpp' with pid 23
> 2018-05-18 17:24:02,245 INFO success: agent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2018-05-18 17:24:02,250 DEBG 'vpp' stdout output:
> vlib_plugin_early_init:356: plugin path /usr/lib/vpp_plugins
> 
> 2018-05-18 17:24:02,251 DEBG 'vpp' stdout output:
> load_one_plugin:184: Loaded plugin: acl_plugin.so (Access Control Lists)

Is there any other step(s), that I need to follow?

**Comment by ondrej-fabry** [comment]
I don't see any particular error. The only strange thing is that VPP process seem to have crashed: `2018-05-18 17:24:01,241 INFO exited: vpp (terminated by SIGABRT (core dumped); not expected)`

Closing this due age. Please open new issue if you run into some problem again.
