### ISSUE TITLE
vpp-agent integration/relationship with Contiv-VPP

### ISSUE THREAD

**Issue by edsealing** [ligato/vpp-agent#717]
Hi. I'm struggling to figure out the relationship between ligato/vpp-agent and contiv/vpp. I understand that contive/vpp allows inter-node networking, while ligato/vpp-agent provides the dataplane configuration interface via KV store. However this would suggest that these two projects would need to be tightly coupled in some way.

In the [Deployment.md](https://github.com/ligato/vpp-agent/blob/master/docs/Deployment.md), it briefly states:
```
For integration with Contiv we decided to embed the VPP Agent directly into the netplugin process
```
It makes reference to `TBD` in numerous places. I see a contiv branch that is actively being maintained as well but 180 commits behind master.

Is ligato/vpp and contiv/vpp currently compatible with each other? I'm happy to help with the testing/docs if there is a little more info on how to get started using both Contiv and Ligato together.

**Comment by rastislavszabo** [comment]
Hi,

Contiv/VPP uses ligato/vpp-agent as a framework for programming VPP. ligato/vpp-agent is an imported dependency in Contiv/VPP (se the vendor folder: https://github.com/contiv/vpp/tree/master/vendor/github.com/ligato/vpp-agent). Contiv/VPP extends the base functionality of ligato/vpp-agent - basically integrates with kubernetes API.

**Comment by edsealing** [comment]
Great response. I'll start digging into Contiv/VPP.

Do you know if the [reference scenarios](https://github.com/ligato/vpp-agent/tree/master/k8s/perf-demo) and sfc-controller currently compatible with the Contiv/VPP implementation?

**Comment by brecode** [comment]
@edsealing 

Both should work in theory but you'll need to have matching versions of all the components. In the meantime there is a demo you can try yourself with SFC-controller under the ons-demo branch in Contiv-VPP repo, using vagrant VMs environment: 
[Contiv-VPP and SFC @ONS demo](https://github.com/contiv/vpp/tree/ons-demo/k8s/demo/ons2018)

The demo is not using the latest ligato/vpp-agent . We will merge that branch into master with instructions and a few more examples this upcoming week including also the latest version of SFC controller as we will be moving to v2.1 and the latest ligato/vpp-agent. 

Let us know if you run into any issues.

**Comment by edsealing** [comment]
@brecode Thanks for the heads up. Just got the latest Contiv/VPP up and running on my dev cluster. Looking good so far. Can't wait to play with v2.1 in the upcoming weeks.
