### ISSUE TITLE
vpp-agent features

### ISSUE THREAD

**Issue by zurrehma** [ligato/vpp-agent#872]
is every feature of vpp which is provided here [https://wiki.fd.io/view/VPP/Features](url) is implemented in ligato/vpp-agent or there are some functionalities missing?

**Comment by ondrej-fabry** [comment]
Here is list of VPP features implemented by vpp-agent: 
https://github.com/ligato/vpp-agent/wiki/VPP-compatibility

However it might not be up to date. You can poke around in [vpp plugin](https://github.com/ligato/vpp-agent/tree/master/plugins/vpp) to check specific features.

**Comment by zurrehma** [comment]
@ondrej-fabry e.g when i go to this 
https://github.com/ligato/vpp-agent/wiki/VPP-compatibility link its show me some of the features are not implemented at all and some of them like **l2 plugin** is partially implemented, now my question is if i have to see that which featues of l2 plugin is not implemented then how and which files i have to comapre (e.g do i have to compare .proto file or some other files)?

**Comment by ondrej-fabry** [comment]
You can go to [vppcalls](https://github.com/ligato/vpp-agent/tree/master/plugins/vpp/l2plugin/vppcalls) package in vpp/l2plugin where you will find the most low-level calls we do in l2plugin and this might give you better idea what parts we support.

You can also checkout [l2 model](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/model/l2/l2.proto), which will give you overview from northbound perspective of what we support for this section.

**Comment by zurrehma** [comment]
@ondrej-fabry maybe its a bit odd to ask this but if you can answer me that will be very helpful to me.
1: is going for some existing feature is easy to implement or those who are not implement by you guys at all will be easy?
2:can you just tell me that which feature in the above link are easy to implement?

**Comment by zurrehma** [comment]
@ondrej-fabry can i change this
https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/model/l2/l2.proto .proto file according to my need or its a standard?

**Comment by VladoLavor** [comment]
@zurrehma just fork the project and you can do whatever you want

**Comment by zurrehma** [comment]
why this command **vpp-agent-ctl -put "/vnf-agent/vpp1/vpp/config/v1/bd/bd1" bridge-domain.json** gives error?
what is **vnf-agent**?
