### ISSUE TITLE
how vpp-agent is putting data in to vpp from etcd

### ISSUE THREAD

**Issue by zurrehma** [ligato/vpp-agent#903]
when i run this command **vpp-agent-ctl /opt/vpp-agent/dev/etcd.conf -tap** it dump my data in to etcd somewhere here https://github.com/ligato/vpp-agent/blob/0599866e3291ec0ba252623cf1fcee62ff2a09fe/cmd/vpp-agent-ctl/data_cmd.go#L324 
my question is how **vpp-agent** is putting this above configuration from **etcd** in to vpp?
second thing where we are using **vppcalls** packages in this **vpp-agent-ctl /opt/vpp-agent/dev/etcd.conf -tap** command because the thing which i have understand is this that these **vppcalls** folder in every plugin is communicating with https://github.com/ligato/vpp-agent/tree/master/plugins/vpp/binapi these generated go code and from there we are inserting our connfiguration in to vpp.

**Comment by ondrej-fabry** [comment]
The `vpp-agent-ctl` app simply puts the model (in your case tap interface) filled with the data to the Etcd. If the `vpp-agent` is running or started after this it should read the data from the Etcd or be notified about the change and execute relevant commands needed to create interface in VPP.

Here's document showing the data flow: https://github.com/ligato/vpp-agent/blob/master/docs/Deployment.md#key-value-data-store-for-nb-north-bound

> ![](https://raw.githubusercontent.com/ligato/vpp-agent/master/docs/imgs/deployment_with_data_store.png)

In your case you could say that:
- **Control Plane APP** is the `vpp-agent-ctl`
- **Data Store** is the Etcd
- and rest is vpp-agent + VPP

**Comment by zurrehma** [comment]
How this function https://github.com/ligato/vpp-agent/blob/0599866e3291ec0ba252623cf1fcee62ff2a09fe/examples/localclient_vpp/plugins/main.go#L136
is working ?
where each of the functions which we are calling in this function is implemented?

**Comment by zurrehma** [comment]
@ondrej-fabry while looking at the above example of embedded deployment,after initializing my example plugin and here while putting my initial configuration, this line https://github.com/ligato/vpp-agent/blob/0599866e3291ec0ba252623cf1fcee62ff2a09fe/examples/localclient_vpp/plugins/main.go#L142
is sending me here https://github.com/ligato/vpp-agent/blob/master/clientv1/vpp/data_resync_api.go
and from there i am sending data to this
https://github.com/ligato/vpp-agent/blob/0599866e3291ec0ba252623cf1fcee62ff2a09fe/plugins/vpp/model/interfaces/interfaces.pb.go#L220
this struct in case of memif Interface.
my question is where and how from data after dumping into these structs are going?

**Comment by ondrej-fabry** [comment]
> my question is where and how from data after dumping into these structs are going?

To be honest, I'm not really sure what you're asking here.

Just to summarize, when using _embedded deployment_ (localclient) the data is going in the following flow:

1. [Created and filled](https://github.com/ligato/vpp-agent/blob/0599866e3291ec0ba252623cf1fcee62ff2a09fe/examples/localclient_vpp/plugins/main.go#L137-L141) model using [clientv1 DSL](https://github.com/ligato/vpp-agent/blob/pantheon-dev/clientv1/linux/data_resync_api.go#L38)
2. Data is then [committed](https://github.com/ligato/vpp-agent/blob/0599866e3291ec0ba252623cf1fcee62ff2a09fe/examples/localclient_vpp/plugins/main.go#L142) to Etcd
3. [VPP linux plugin is notified](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/watch_events.go#L44) about resync
4. [Resync is processed and dispatched](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/data_resync.go#L159) to relevant configurators
5. Configurators then [dump current state from VPP](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/ifplugin/data_resync.go#L62)
6. [Dumped state from VPP is compared](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/ifplugin/data_resync.go#L71-L164) to northbound configuration (Etcd) where residual config is [removed from VPP](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/ifplugin/data_resync.go#L159)
7. Config defined in NB and [missing in VPP is then configured](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/ifplugin/data_resync.go#L166-L177)
8. Steps 5-7 are done for each configurator individually.
9. Resync is done when all configurators finish resync

**Comment by zurrehma** [comment]
@ondrej-fabry  if i am using key value data store (etcd) then what will be change in above steps?
in my opinion there will be changes before step 3.
step 3,4,5,6,7 and 8 will be same.

**Comment by ondrej-fabry** [comment]
That's correct.

**Comment by zurrehma** [comment]
@ondrej-fabry why we write these  [test files](https://github.com/ligato/vpp-agent/blob/master/plugins/vpp/l2plugin/vppcalls/bridge_domain_vppcalls_test.go) ?
can i use them to send data to vpp for testing purpose without using north bound api and proto models?

**Comment by ondrej-fabry** [comment]
These tests are testing behaviour of vppcalls handlers and they mock VPP replies as you can see in `bdTestSetup`:

https://github.com/ligato/vpp-agent/blob/304803473863d0503ebc4fc7bb01099559ccf0ec/plugins/vpp/l2plugin/vppcalls/bridge_domain_vppcalls_test.go#L139

**Comment by ondrej-fabry** [comment]
```
$ go test -v -run 'Vpp.*BridgeDomain' ./plugins/vpp/l2plugin/vppcalls
```

**Comment by zurrehma** [comment]
@ondrej-fabry  as you have told me earlier that vpp-agent-ctl or every [example](https://github.com/ligato/vpp-agent/tree/d2ae51e30bb34e5dec059de71c2d0f42ecb10a09/examples) is a plugin because we first register it with cn-infra.
my question is each plugin of [vpp](https://github.com/ligato/vpp-agent/tree/d2ae51e30bb34e5dec059de71c2d0f42ecb10a09/plugins/vpp) which you have defined here, **In which files are you registering these plugins** ?

**Comment by ondrej-fabry** [comment]
The plugins inside vpp folder are registered in `plugin_impl_vpp.go` file.

https://github.com/ligato/vpp-agent/blob/d2ae51e30bb34e5dec059de71c2d0f42ecb10a09/plugins/vpp/plugin_impl_vpp.go#L300-L320

**Comment by zurrehma** [comment]
@ondrej-fabry when i run go test via this command 
go test -v -run 'Vpp.*BridgeDomain' ./plugins/vpp/l2plugin/vppcalls
why it gives me this error?

root@60d852874a4d:~/go/src/github.com/ligato/vpp-agent# go test -v -run 'Vpp.*BridgeDomain' ./plugins/vpp/l2plugin/vppcalls
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls.go:22:2: cannot find package "git.fd.io/govpp.git/api" in any of:
	/usr/local/go/src/git.fd.io/govpp.git/api (from $GOROOT)
	/go/src/git.fd.io/govpp.git/api (from $GOPATH)
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls.go:23:2: cannot find package "github.com/ligato/cn-infra/logging" in any of:
	/usr/local/go/src/github.com/ligato/cn-infra/logging (from $GOROOT)
	/go/src/github.com/ligato/cn-infra/logging (from $GOPATH)
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls.go:24:2: cannot find package "github.com/ligato/cn-infra/logging/measure" in any of:
	/usr/local/go/src/github.com/ligato/cn-infra/logging/measure (from $GOROOT)
	/go/src/github.com/ligato/cn-infra/logging/measure (from $GOPATH)
plugins/vpp/l2plugin/vppcalls/arp_term_vppcalls.go:25:2: cannot find package "github.com/ligato/cn-infra/utils/addrs" in any of:
	/usr/local/go/src/github.com/ligato/cn-infra/utils/addrs (from $GOROOT)
	/go/src/github.com/ligato/cn-infra/utils/addrs (from $GOPATH)
root@60d852874a4d:~/go/src/github.com/ligato/vpp-agent#

**Comment by ondrej-fabry** [comment]
Did you by any chance alter contents of vendor directory? What go version are you running?

**Comment by zurrehma** [comment]
@ondrej-fabry  i don't think so that i have changed something in vendor directory.
go version is **go version go1.10.3 linux/amd64** .

**Comment by zurrehma** [comment]
@ondrej-fabry i have mounted my docker image to my local repository.Is this creating any problem?

**Comment by zurrehma** [comment]
@ondrej-fabry test is working now.
On which branch are you guys developing this code for vpp-agent, maybe fetching it and seeing your commits from start will give me better understanding of how to start with developing a plugin.

**Comment by zurrehma** [comment]
@ondrej-fabry  i want to know that where [this](https://github.com/ligato/vpp-agent/blob/0599866e3291ec0ba252623cf1fcee62ff2a09fe/examples/localclient_vpp/plugins/main.go#L138) function is implemented?

**Comment by VladoLavor** [comment]
@zurrehma the function is implemented [here](https://github.com/ligato/vpp-agent/blob/pantheon-dev/clientv1/vpp/data_resync_api.go). Notice that there are two folders in the clientv1 package - vpp, and linux. The vpp package contains only vpp calls, the linux package contains linux and vpp calls (a kind of extension of the vpp clientv1).

**Comment by zurrehma** [comment]
@ondrej-fabry ,   suppose i have written a new plugin, and want to integrate it with clientv1/[vpp](https://github.com/ligato/vpp-agent/tree/pantheon-dev/clientv1/vpp).
To my understanding following will be done in case of local-client:
1: implementing interface signature [here](https://github.com/ligato/vpp-agent/blob/pantheon-dev/clientv1/vpp/data_resync_api.go) .
2: implementing above interface signature functionality [here](https://github.com/ligato/vpp-agent/blob/pantheon-dev/clientv1/vpp/dbadapter/data_resync_db.go).
 When this will be done and whenever this [function ](https://github.com/ligato/vpp-agent/blob/a8ba60fe5c790a9f83652ba46f06b94e5fc218dd/clientv1/vpp/dbadapter/data_resync_db.go#L250) will be invoked, after this [line](https://github.com/ligato/vpp-agent/blob/a8ba60fe5c790a9f83652ba46f06b94e5fc218dd/clientv1/vpp/dbadapter/data_resync_db.go#L354) invocation this will now be the job of "github.com/ligato/cn-infra/db/keyval" because [txn](https://github.com/ligato/vpp-agent/blob/a8ba60fe5c790a9f83652ba46f06b94e5fc218dd/clientv1/vpp/dbadapter/data_resync_db.go#L43) is of  keyval.ProtoTxn type.
now my question are:
1: is my perceiving is right?
2: Do we have to write some code in **cn-infra/db/keyval** part because our **txn** is of that type?

**Comment by ondrej-fabry** [comment]
Closing as this issue is obsolete for Agent v2.
